# Generated by Django 5.2.14 on 2026-06-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdownload',
            name='snapshot_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvdownload',
            name='template_slug',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
