# Generated by Django 5.2.14 on 2026-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_cvdownload_snapshot_html_cvdownload_template_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=120)),
                ('card_number', models.CharField(max_length=40)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
