RESUME_TEMPLATES = [
    {'slug': 'artistic', 'name': 'Artistic', 'preview': 'images/templates/artistic.jpg', 'template': 'resume_templates/artistic.html'},
    {'slug': 'bloom', 'name': 'Bloom', 'preview': 'images/templates/bloom.jpg', 'template': 'resume_templates/bloom.html'},
    {'slug': 'timeless', 'name': 'Timeless', 'preview': 'images/templates/timeless.jpg', 'template': 'resume_templates/timeless.html'},
    {'slug': 'impact', 'name': 'Impact', 'preview': 'images/templates/impact.jpg', 'template': 'resume_templates/impact.html'},
    {'slug': 'expert', 'name': 'Expert', 'preview': 'images/templates/expert.jpg', 'template': 'resume_templates/expert.html'},
    {'slug': 'elite', 'name': 'Elite', 'preview': 'images/templates/elite.jpg', 'template': 'resume_templates/elite.html'},
    {'slug': 'elevate', 'name': 'Elevate', 'preview': 'images/templates/elevate.jpg', 'template': 'resume_templates/elevate.html'},
    {'slug': 'modular', 'name': 'Modular', 'preview': 'images/templates/modular.jpg', 'template': 'resume_templates/modular.html'},
    {'slug': 'classic', 'name': 'Classic', 'preview': 'images/templates/classic.jpg', 'template': 'resume_templates/classic.html'},
    {'slug': 'luxe', 'name': 'Luxe', 'preview': 'images/templates/luxe.jpg', 'template': 'resume_templates/luxe.html'},
    {'slug': 'contemporary', 'name': 'Contemporary', 'preview': 'images/templates/contemporary.jpg', 'template': 'resume_templates/contemporary.html'},
    {'slug': 'functional', 'name': 'Functional', 'preview': 'images/templates/functional.jpg', 'template': 'resume_templates/functional.html'},
    {'slug': 'enterprise', 'name': 'Enterprise', 'preview': 'images/templates/enterprise.jpg', 'template': 'resume_templates/enterprise.html'},
    {'slug': 'engage', 'name': 'Engage', 'preview': 'images/templates/engage.jpg', 'template': 'resume_templates/engage.html'},
    {'slug': 'professional', 'name': 'Professional', 'preview': 'images/templates/professional.jpg', 'template': 'resume_templates/professional.html'},
    {'slug': 'streamline', 'name': 'Streamline', 'preview': 'images/templates/streamline.jpg', 'template': 'resume_templates/streamline.html'},
    {'slug': 'confident', 'name': 'Confident', 'preview': 'images/templates/confident.jpg', 'template': 'resume_templates/confident.html'},
    {'slug': 'prestige', 'name': 'Prestige', 'preview': 'images/templates/prestige.jpg', 'template': 'resume_templates/prestige.html'},
]
